# Site settings
title: Lucky Mercy
subtitle: "Web and Clothing"
email: lucky79mercy@yahoo.com
description: "Web and Clothing"
baseurl:  "https://luckymercy.github.io"
url:  "https://luckymercy.github.io"
twitter_username: lucky79mercy
github_username:  lucky79mercy

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


